<?php
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Extension\InfoParser;
/**
 * Implements hook_help().
 */
function smplphotoalbum_help($route_name, RouteMatchInterface $route_match) {
  global $language;
  $output = '';
  
  switch ($route_name) {
    case "help.page.smplphotoalbum" :
      $output = '<h3>' . t ( 'About' ) . '</h3>';
      $path = drupal_get_path ( 'module', 'smplphotoalbum' ) . '/smplphotoalbum.info.yml';
      $InfoParsed = new InfoParser ();
      $info = $InfoParsed->parse ( $path );
      $output .= 'Author: <a href="http://www.fzolee.hu">Zoltan Fabian</a><br/>';
      $output .= t ( 'version' ) . ': ' . $info ['version'] . '<br/>';
      $output .= t ( 'compiled' ) . ': ' . date ( 'Y.m.d', $info ['datestamp'] );
      $output .= "<p>" . t ( "Simple Photoalbum shows a set of picture and other filetypes ." ) . "</p>";
      $lang = \Drupal::languageManager ()->getCurrentLanguage ();
      if ($lang->getId () == "hu") {
        $output .= file_get_contents ( drupal_get_path ( 'module', 'smplphotoalbum' ) . "/Olvassel.html" );
      } else {
        $output .= file_get_contents ( drupal_get_path ( 'module', 'smplphotoalbum' ) . "/Readme.html" );
      }
  }
  return $output;
}
/*
 * function smplphotoalbum_preprocess_page(&$variables) {
 * $variables['#attached']['library'][] = "smplphotoalbum/css";
 * }
 */
/**
 * Hook_theme() - for use twig templates
 * 
 * @param unknown $existing          
 * @param unknown $type          
 * @param unknown $theme          
 * @param unknown $path          
 * @return NULL[][][]
 */
function smplphotoalbum_theme($existing, $type, $theme, $path) {
  $theme = [ 
      'smplphotoalbum' => [ 
          'variables' => [ 
              'valami változo' => NULL 
          ] 
      ],
      'editform' => [ 
          'variables' => [ 
              'var1' => NULL 
          ] 
      ],
      'imageeditform' => [ 
          'variables' => [ 
              'var2' => NULL 
          ] 
      ] 
  ];
  
  return $theme;
}